/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package org.apache.baremaps.osm.pbf;

import static org.apache.baremaps.stream.ConsumerUtils.consumeThenReturn;

import java.io.InputStream;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Stream;
import org.apache.baremaps.collection.LongDataMap;
import org.apache.baremaps.osm.OsmReader;
import org.apache.baremaps.osm.function.BlockEntityConsumer;
import org.apache.baremaps.osm.function.CreateGeometryConsumer;
import org.apache.baremaps.osm.function.ReprojectEntityConsumer;
import org.apache.baremaps.osm.model.Blob;
import org.apache.baremaps.osm.model.Block;
import org.apache.baremaps.osm.model.Entity;
import org.apache.baremaps.osm.store.DataStoreConsumer;
import org.apache.baremaps.stream.StreamUtils;
import org.locationtech.jts.geom.Coordinate;

/** A utility class for reading an OpenStreetMap pbf file. */
public class PbfBlockReader implements OsmReader<Block> {

  private int buffer = Runtime.getRuntime().availableProcessors();

  private boolean geometry = false;

  private int srid = 4326;

  private LongDataMap<Coordinate> coordinates;

  private LongDataMap<List<Long>> references;

  /**
   * Gets the number of blobs buffered by the parser to parallelize deserialization.
   *
   * @return the size of the buffer
   */
  public int buffer() {
    return buffer;
  }

  /**
   * Sets the number of blobs buffered by the parser to parallelize deserialization.
   *
   * @param buffer the size of the buffer
   * @return the parser
   */
  public PbfBlockReader buffer(int buffer) {
    this.buffer = buffer;
    return this;
  }

  /**
   * Gets the flag enabling the generation of geometries.
   *
   * @return the value of the flag
   */
  public boolean geometries() {
    return geometry;
  }

  /**
   * Sets the flag enabling the generation of geometries.
   *
   * @param geometries the value of the flag
   * @return the parser
   */
  public PbfBlockReader geometries(boolean geometries) {
    this.geometry = geometries;
    return this;
  }

  /**
   * Gets the projection of the geometries generated by this parser.
   *
   * @return the projection of the geometries
   */
  public int projection() {
    return srid;
  }

  /**
   * Sets the projection of the geometries generated by this parser.
   *
   * @param srid the projection of the geometries
   * @return the parser
   */
  public PbfBlockReader projection(int srid) {
    this.srid = srid;
    return this;
  }

  /**
   * Gets the map used to store coordinates for generating geometries.
   *
   * @return the map of coordinates
   */
  public LongDataMap<Coordinate> coordinates() {
    return coordinates;
  }

  /**
   * Sets the map used to store coordinates for generating geometries.
   *
   * @param coordinates the map of coordinates
   * @return the parser
   */
  public PbfBlockReader coordinates(LongDataMap<Coordinate> coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  /**
   * Gets the map used to store references for generating geometries.
   *
   * @return the map of references
   */
  public LongDataMap<List<Long>> references() {
    return references;
  }

  /**
   * Sets the map used to store references for generating geometries.
   *
   * @param references the map of references
   * @return the parser
   */
  public PbfBlockReader references(LongDataMap<List<Long>> references) {
    this.references = references;
    return this;
  }

  /**
   * Creates an ordered stream of blocks.
   *
   * @param inputStream an osm pbf {@link InputStream}
   * @return a stream of blocks
   */
  public Stream<Block> stream(InputStream inputStream) {
    Stream<Block> blocks =
        StreamUtils.bufferInSourceOrder(StreamUtils.stream(new BlobIterator(inputStream)),
            this::read, Runtime.getRuntime().availableProcessors());
    if (geometry) {
      Consumer<Block> cacheBlock = new DataStoreConsumer(coordinates, references);
      Consumer<Entity> createGeometry = new CreateGeometryConsumer(coordinates, references);
      if (srid != 4326) {
        Consumer<Entity> reprojectGeometry = new ReprojectEntityConsumer(4326, srid);
        createGeometry = createGeometry.andThen(reprojectGeometry);
      }
      Consumer<Block> prepareGeometries = new BlockEntityConsumer(createGeometry);
      Function<Block, Block> prepareBlock =
          consumeThenReturn(cacheBlock.andThen(prepareGeometries));
      blocks = blocks.map(prepareBlock);
    }
    return blocks;
  }

  public Block read(Blob blob) {
    switch (blob.header().getType()) {
      case "OSMHeader":
        return HeaderBlockReader.read(blob);
      case "OSMData":
        return DataBlockReader.read(blob);
      default:
        throw new RuntimeException("Unknown blob type");
    }
  }
}
