version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - bchapuis
  ignore:
  - dependency-name: software.amazon.awssdk:s3
    versions:
    - 2.15.57
    - 2.15.73
    - 2.16.8
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.27"
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.27"
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-xml
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: com.google.dagger:dagger
    versions:
    - 2.30.1
    - 2.31.2
