/**
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 in compliance with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software distributed under the License
 is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 or implied. See the License for the specific language governing permissions and limitations under
 the License.
 **/
 import theme from "../../theme.js";

export default [
    {
        id: 'dormitory_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'building'], 'dormitory'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                9,
                17,
                10,
                18,
                11,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.dormitoryLabelsTextColor,
            'text-halo-color': theme.dormitoryLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'quarry_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'landuse'], 'quarry'], ['>=', ['zoom'], 16]],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                12,
                17,
                14,
                18,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.quarryLabelsTextColor,
            'text-halo-color': theme.quarryLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'building_school_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'building'], 'school'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                9,
                17,
                10,
                18,
                11,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.buildingSchoolLabelsTextColor,
            'text-halo-color': theme.buildingSchoolLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'building_labels',
        type: 'symbol',
        filter: [
            'all',
            [
                'any',
                ['==', ['get', 'building'], 'hospital'],
                ['==', ['get', 'building'], 'yes'],
            ],
            ['!', ['has', 'amenity']],
            ['!', ['has', 'historic']],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                9,
                17,
                10,
                18,
                11,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.buildingLabelsTextColor,
            'text-halo-color': theme.buildingLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'social_facility_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'social_facility'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': theme.socialFacilityLabelsTextColor,
            'text-halo-color': theme.socialFacilityLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.socialFacilityLabelsIconColor,
            'icon-halo-color': theme.socialFacilityLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'pitch_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'leisure'], 'pitch'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                10,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.pitchLabelsTextColor,
            'text-halo-color': theme.pitchLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'theatre_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'theatre'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': theme.theatreLabelsTextColor,
            'text-halo-color': theme.theatreLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.theatreLabelsIconColor,
            'icon-halo-color': theme.theatreLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'community_centre_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'community_centre'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': theme.communityCentreLabelsTextColor,
            'text-halo-color': theme.communityCentreLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.communityCentreLabelsIconColor,
            'icon-halo-color': theme.communityCentreLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'sports_hall_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'leisure'], 'sports_hall'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                10,
                17,
                14,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.sportHallLabelsTextColor,
            'text-halo-color': theme.sportHallLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'school_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'amenity'], 'school'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                9,
                17,
                14,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.schoolLabelsTextColor,
            'text-halo-color': theme.schoolLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'college_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'college'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                10,
                17,
                14,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.collegeLabelsTextColor,
            'text-halo-color': theme.collegeLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'courthouse_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'courthouse'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': theme.courthouseLabelsTextColor,
            'text-halo-color': theme.courthouseLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.courthouseLabelsIconColor,
            'icon-halo-color': theme.courthouseLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'parking_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'parking'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                9,
                18,
                11,
            ],
            'text-anchor': 'top',
            'text-optional': true,
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.parkingLabelsTextColor,
            'text-halo-color': theme.parkingLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.parkingLabelsIconColor,
            'icon-halo-color': theme.parkingLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'industrial_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'landuse'], 'industrial'],
            ['>=', ['zoom'], 14],
        ],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                14,
                10,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.industrialLabelsTextColor,
            'text-halo-color': theme.industrialLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },

    {
        id: 'poi_cafes',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'amenity'], 'cafe'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'cafe',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poicafeTextColor,
            'icon-color': theme.poicafeIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poicafeIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poicafeTextHaloColor,
        },
    },
    {
        id: 'poi_atm',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'amenity'], 'atm'], ['>=', ['zoom'], 16]],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'atm',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiAtmTextColor,
            'icon-color': theme.poiAtmIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiAtmIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiAtmTextHaloColor,
        },
    },
    {
        id: 'poi_fuel_charging',
        type: 'symbol',
        filter: [
            'all',
            ['in', ['get', 'amenity'], ['literal', ['charging_station', 'fuel']]],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiFuelChargingTextColor,
            'icon-color': theme.poiFuelChargingIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiFuelChargingIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiFuelChargingTextHaloColor,
        },
    },
    {
        id: 'poi_parkings',
        type: 'symbol',
        filter: [
            'all',
            [
                'any',
                [
                    'all',
                    ['==', ['get', 'amenity'], 'parking_entrance'],
                    ['==', ['get', 'parking'], 'underground'],
                ],
                [
                    'in',
                    ['get', 'amenity'],
                    ['literal', ['parking', 'motorcycle_parking']],
                ],
            ],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiParkingTextColor,
            'icon-color': theme.poiParkingIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiParkingIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiParkingTextHaloColor,
        },
    },
    {
        id: 'poi_hotels',
        type: 'symbol',
        filter: [
            'all',
            [
                'in',
                ['get', 'tourism'],
                ['literal', ['guest_house', 'hostel', 'hotel', 'motel']],
            ],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'tourism'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiHotelTextColor,
            'icon-color': theme.poiHotelIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiHotelIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiHotelTextHaloColor,
        },
    },
    {
        id: 'poi_shops',
        type: 'symbol',
        filter: [
            'any',
            [
                'all',
                [
                    'in',
                    ['get', 'shop'],
                    ['literal', ['department_store', 'supermarket']],
                ],
                ['>=', ['zoom'], 15],
            ],
            [
                'all',
                [
                    'in',
                    ['get', 'shop'],
                    [
                        'literal',
                        [
                            'alcohol',
                            'bakery',
                            'beverages',
                            'butcher',
                            'coffee',
                            'confectionery',
                            'convenience',
                            'deli',
                            'dairy',
                            'greengrocer',
                            'tea',
                            'department_store',
                            'supermarket',
                            'bag',
                            'clothes',
                            'fabric',
                            'jewelry',
                            'shoes',
                            'charity',
                            'second_hand',
                            'variety_store',
                            'beauty',
                            'chemist',
                            'hairdresser',
                            'medical_supply',
                            'optician',
                            'perfumery',
                            'florist',
                            'garden_centre',
                            'houseware',
                            'paint',
                            'trade',
                            'bed',
                            'carpet',
                            'furniture',
                            'interior_decoration',
                            'computer',
                            'electronics',
                            'hifi',
                            'mobile_phone',
                            'bicycle',
                            'boat',
                            'car',
                            'car_repair',
                            'motorcycle',
                            'outdoor',
                            'sports',
                            'tyres',
                            'art',
                            'music',
                            'musical_instrument',
                            'photo',
                            'video',
                            'video_games',
                            'gift',
                            'newsagent',
                            'stationery',
                            'ticket',
                            'bookmaker',
                            'copyshop',
                            'laundry',
                            'pet',
                            'tobacco',
                            'toys',
                            'travel_agency',
                            'massage',
                        ],
                    ],
                ],
                ['>=', ['zoom'], 17],
            ],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'shop'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': [
                'case',
                [
                    'in',
                    ['get', 'shop'],
                    [
                        'literal',
                        [
                            'alcohol',
                            'bakery',
                            'beverages',
                            'butcher',
                            'coffee',
                            'confectionery',
                            'convenience',
                            'deli',
                            'dairy',
                            'greengrocer',
                            'tea',
                            'department_store',
                            'supermarket',
                            'bag',
                            'clothes',
                            'fabric',
                            'jewelry',
                            'shoes',
                            'charity',
                            'second_hand',
                            'variety_store',
                            'beauty',
                            'chemist',
                            'hairdresser',
                            'medical_supply',
                            'optician',
                            'perfumery',
                            'florist',
                            'garden_centre',
                            'houseware',
                            'paint',
                            'trade',
                            'bed',
                            'carpet',
                            'furniture',
                            'interior_decoration',
                            'computer',
                            'electronics',
                            'hifi',
                            'mobile_phone',
                            'bicycle',
                            'boat',
                            'car',
                            'car_repair',
                            'motorcycle',
                            'outdoor',
                            'sports',
                            'tyres',
                            'art',
                            'music',
                            'musical_instrument',
                            'photo',
                            'video',
                            'video_games',
                            'gift',
                            'newsagent',
                            'stationery',
                            'ticket',
                            'bookmaker',
                            'copyshop',
                            'laundry',
                            'pet',
                            'tobacco',
                            'toys',
                            'travel_agency',
                        ],
                    ],
                ],
                theme.poiShopsTextColorLiteral,
                ['==', ['get', 'shop'], 'massage'],
                theme.poiShopsTextColorMassage,
                theme.poiShopsTextColor,
            ],
            'icon-color': [
                'case',
                [
                    'in',
                    ['get', 'shop'],
                    [
                        'literal',
                        [
                            'alcohol',
                            'bakery',
                            'beverages',
                            'butcher',
                            'coffee',
                            'confectionery',
                            'convenience',
                            'deli',
                            'dairy',
                            'greengrocer',
                            'tea',
                            'department_store',
                            'supermarket',
                            'bag',
                            'clothes',
                            'fabric',
                            'jewelry',
                            'shoes',
                            'charity',
                            'second_hand',
                            'variety_store',
                            'beauty',
                            'chemist',
                            'hairdresser',
                            'medical_supply',
                            'optician',
                            'perfumery',
                            'florist',
                            'garden_centre',
                            'houseware',
                            'paint',
                            'trade',
                            'bed',
                            'carpet',
                            'furniture',
                            'interior_decoration',
                            'computer',
                            'electronics',
                            'hifi',
                            'mobile_phone',
                            'bicycle',
                            'boat',
                            'car',
                            'car_repair',
                            'motorcycle',
                            'outdoor',
                            'sports',
                            'tyres',
                            'art',
                            'music',
                            'musical_instrument',
                            'photo',
                            'video',
                            'video_games',
                            'gift',
                            'newsagent',
                            'stationery',
                            'ticket',
                            'bookmaker',
                            'copyshop',
                            'laundry',
                            'pet',
                            'tobacco',
                            'toys',
                            'travel_agency',
                        ],
                    ],
                ],
                theme.poiShopsIconColorLiteral,
                ['==', ['get', 'shop'], 'massage'],
                theme.poiShopsIconColorMassage,
                theme.poiShopsIconColor,
            ],
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiShopsIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiShopsTextHaloColor,
        },
    },
    {
        id: 'poi_restaurants',
        type: 'symbol',
        filter: [
            'all',
            ['in', ['get', 'amenity'], ['literal', ['restaurant', 'food_court']]],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'restaurant',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiRestaurantsTextColor,
            'icon-color': theme.poiRestaurantsIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiReaturantsIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiRestaurantsTextHaloColor,
        },
    },
    {
        id: 'poi_fast-food',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'fast_food'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'fast_food',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiFastFoodTextColor,
            'icon-color': theme.poiFastFoodIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiFastFoodIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiFastFoodTextHaloColor,
        },
    },
    {
        id: 'poi_bars/pubs',
        type: 'symbol',
        filter: [
            'all',
            ['in', ['get', 'amenity'], ['literal', ['bar', 'biergarten', 'pub']]],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiBarPubTextColor,
            'icon-color': theme.poiBarPubIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiBarPubIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiBarPubTextHaloColor,
        },
    },
    {
        id: 'poi_pharmacies',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'pharmacy'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'pharmacy',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': theme.poiPharmacieTextColor,
            'icon-color': theme.poiPharmacieIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': theme.poiPharmacieIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': theme.poiPharmacieTextHaloColor,
        },
    },
    {
        id: 'zoo_labels',
        type: 'symbol',
        filter: ['all', ['==', 'tourism', 'zoo']],
        source: 'baremaps',
        'source-layer': 'tourism',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Bold'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                13,
                12,
                16,
                16,
                18,
                20,
            ],
        },
        paint: {
            'text-color': theme.zooLabelsTextColor,
            'text-halo-color': theme.zooLabelsTextHaloColor,
            'text-halo-width': 1,
        },
    },
    {
        id: 'monument_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'historic'], 'monument'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'historic'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': theme.monumentLabelsTextColor,
            'text-halo-color': theme.monumentLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.monumentLabelsIconColor,
            'icon-halo-color': theme.monumentLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'cemetery_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'landuse'], 'cemetery'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                10,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.cemeteryLabelsTextColor,
            'text-halo-color': theme.cemeteryLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'forest_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'landuse'], 'forest'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                12,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.forestLabelsTextColor,
            'text-halo-color': theme.forestLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'stadium_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'leisure'], 'stadium'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                9,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.stadiumLabelsTextColor,
            'text-halo-color': theme.stadiumLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'park_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'leisure'], 'park'], ['>=', ['zoom'], 14]],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                14,
                10,
                17,
                18,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': theme.parkLabelsTextColor,
            'text-halo-color': theme.parkLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'hospital_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'hospital'],
            ['>=', ['zoom'], 14],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['step', ['zoom'], '', 14, '', 15, ['get', 'name']],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': theme.hopitalLabelsTextColor,
            'text-halo-color': theme.hopitalLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': theme.hopitalLabelsIconColor,
            'icon-halo-color': theme.hopitalLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'motorway_junction_ref',
        type: 'symbol',
        filter: ['all', ['==', 'highway', 'motorway_junction']],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'ref'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                10,
                9,
                11,
                9.5,
                12,
                10,
            ],
        },
        maxzoom: 12,
        paint: {
            'text-color': theme.motorwayJunctionRefTextColor,
            'text-halo-color': theme.motorwayJunctionRefTextHaloColor,
            'text-halo-width': 1.2,
        },
    },
    {
        id: 'motorway_junction_name',
        type: 'symbol',
        filter: ['all', ['==', 'highway', 'motorway_junction']],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['format', ['get', 'name'], '\n', ['get', 'ref']],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                12,
                9,
                15,
                10,
                18,
                11,
            ],
        },
        minzoom: 12,
        paint: {
            'text-color': theme.motorwayJunctionNameTextColor,
            'text-halo-color': theme.motorwayJunctionNameTextHaloColor,
            'text-halo-width': 1.2,
        },
    },
]
