/**
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 in compliance with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software distributed under the License
 is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 or implied. See the License for the specific language governing permissions and limitations under
 the License.
 **/
 import colorScheme from "../../theme.js";

export default [
    {
        id: 'dormitory_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'building'], 'dormitory'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                9,
                17,
                10,
                18,
                11,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleDormitoryLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleDormitoryLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'quarry_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'landuse'], 'quarry'], ['>=', ['zoom'], 16]],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                12,
                17,
                14,
                18,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleQuarryLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleQuarryLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'building_school_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'building'], 'school'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                9,
                17,
                10,
                18,
                11,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleBuildingSchoolLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleBuildingSchoolLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'building_labels',
        type: 'symbol',
        filter: [
            'all',
            [
                'any',
                ['==', ['get', 'building'], 'hospital'],
                ['==', ['get', 'building'], 'yes'],
            ],
            ['!', ['has', 'amenity']],
            ['!', ['has', 'historic']],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                9,
                17,
                10,
                18,
                11,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleBuildingLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleBuildingLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'social_facility_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'social_facility'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': colorScheme.labelsStyleSocialFacilityLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleSocialFacilityLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleSocialFacilityLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleSocialFacilityLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'pitch_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'leisure'], 'pitch'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                10,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStylePitchLabelsTextColor,
            'text-halo-color': colorScheme.labelsStylePitchLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'theatre_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'theatre'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': colorScheme.labelsStyleTheatreLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleTheatreLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleTheatreLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleTheatreLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'community_centre_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'community_centre'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': colorScheme.labelsStyleCommunityCentreLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleCommunityCentreLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleCommunityCentreLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleCommunityCentreLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'sports_hall_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'leisure'], 'sports_hall'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                16,
                10,
                17,
                14,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleSportHallLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleSportHallLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'school_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'amenity'], 'school'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                9,
                17,
                14,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleSchoolLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleSchoolLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'college_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'college'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                10,
                17,
                14,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleCollegeLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleCollegeLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'courthouse_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'courthouse'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': colorScheme.labelsStyleCourthouseLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleCourthouseLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleCourthouseLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleCourthouseLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'parking_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'parking'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                9,
                18,
                11,
            ],
            'text-anchor': 'top',
            'text-optional': true,
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleParkingLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleParkingLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleParkingLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleParkingLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'industrial_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'landuse'], 'industrial'],
            ['>=', ['zoom'], 14],
        ],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                14,
                10,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleIndustrialLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleIndustrialLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },

    {
        id: 'poi_cafes',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'amenity'], 'cafe'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'cafe',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoicafeTextColor,
            'icon-color': colorScheme.labelsStylePoicafeIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoicafeIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoicafeTextHaloColor,
        },
    },
    {
        id: 'poi_atm',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'amenity'], 'atm'], ['>=', ['zoom'], 16]],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'atm',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiAtmTextColor,
            'icon-color': colorScheme.labelsStylePoiAtmIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiAtmIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiAtmTextHaloColor,
        },
    },
    {
        id: 'poi_fuel_charging',
        type: 'symbol',
        filter: [
            'all',
            ['in', ['get', 'amenity'], ['literal', ['charging_station', 'fuel']]],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiFuelChargingTextColor,
            'icon-color': colorScheme.labelsStylePoiFuelChargingIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiFuelChargingIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiFuelChargingTextHaloColor,
        },
    },
    {
        id: 'poi_parkings',
        type: 'symbol',
        filter: [
            'all',
            [
                'any',
                [
                    'all',
                    ['==', ['get', 'amenity'], 'parking_entrance'],
                    ['==', ['get', 'parking'], 'underground'],
                ],
                [
                    'in',
                    ['get', 'amenity'],
                    ['literal', ['parking', 'motorcycle_parking']],
                ],
            ],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiParkingTextColor,
            'icon-color': colorScheme.labelsStylePoiParkingIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiParkingIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiParkingTextHaloColor,
        },
    },
    {
        id: 'poi_hotels',
        type: 'symbol',
        filter: [
            'all',
            [
                'in',
                ['get', 'tourism'],
                ['literal', ['guest_house', 'hostel', 'hotel', 'motel']],
            ],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'tourism'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiHotelTextColor,
            'icon-color': colorScheme.labelsStylePoiHotelIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiHotelIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiHotelTextHaloColor,
        },
    },
    {
        id: 'poi_shops',
        type: 'symbol',
        filter: [
            'any',
            [
                'all',
                [
                    'in',
                    ['get', 'shop'],
                    ['literal', ['department_store', 'supermarket']],
                ],
                ['>=', ['zoom'], 15],
            ],
            [
                'all',
                [
                    'in',
                    ['get', 'shop'],
                    [
                        'literal',
                        [
                            'alcohol',
                            'bakery',
                            'beverages',
                            'butcher',
                            'coffee',
                            'confectionery',
                            'convenience',
                            'deli',
                            'dairy',
                            'greengrocer',
                            'tea',
                            'department_store',
                            'supermarket',
                            'bag',
                            'clothes',
                            'fabric',
                            'jewelry',
                            'shoes',
                            'charity',
                            'second_hand',
                            'variety_store',
                            'beauty',
                            'chemist',
                            'hairdresser',
                            'medical_supply',
                            'optician',
                            'perfumery',
                            'florist',
                            'garden_centre',
                            'houseware',
                            'paint',
                            'trade',
                            'bed',
                            'carpet',
                            'furniture',
                            'interior_decoration',
                            'computer',
                            'electronics',
                            'hifi',
                            'mobile_phone',
                            'bicycle',
                            'boat',
                            'car',
                            'car_repair',
                            'motorcycle',
                            'outdoor',
                            'sports',
                            'tyres',
                            'art',
                            'music',
                            'musical_instrument',
                            'photo',
                            'video',
                            'video_games',
                            'gift',
                            'newsagent',
                            'stationery',
                            'ticket',
                            'bookmaker',
                            'copyshop',
                            'laundry',
                            'pet',
                            'tobacco',
                            'toys',
                            'travel_agency',
                            'massage',
                        ],
                    ],
                ],
                ['>=', ['zoom'], 17],
            ],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'shop'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': [
                'case',
                [
                    'in',
                    ['get', 'shop'],
                    [
                        'literal',
                        [
                            'alcohol',
                            'bakery',
                            'beverages',
                            'butcher',
                            'coffee',
                            'confectionery',
                            'convenience',
                            'deli',
                            'dairy',
                            'greengrocer',
                            'tea',
                            'department_store',
                            'supermarket',
                            'bag',
                            'clothes',
                            'fabric',
                            'jewelry',
                            'shoes',
                            'charity',
                            'second_hand',
                            'variety_store',
                            'beauty',
                            'chemist',
                            'hairdresser',
                            'medical_supply',
                            'optician',
                            'perfumery',
                            'florist',
                            'garden_centre',
                            'houseware',
                            'paint',
                            'trade',
                            'bed',
                            'carpet',
                            'furniture',
                            'interior_decoration',
                            'computer',
                            'electronics',
                            'hifi',
                            'mobile_phone',
                            'bicycle',
                            'boat',
                            'car',
                            'car_repair',
                            'motorcycle',
                            'outdoor',
                            'sports',
                            'tyres',
                            'art',
                            'music',
                            'musical_instrument',
                            'photo',
                            'video',
                            'video_games',
                            'gift',
                            'newsagent',
                            'stationery',
                            'ticket',
                            'bookmaker',
                            'copyshop',
                            'laundry',
                            'pet',
                            'tobacco',
                            'toys',
                            'travel_agency',
                        ],
                    ],
                ],
                colorScheme.labelsStylePoiShopsTextColorLiteral,
                ['==', ['get', 'shop'], 'massage'],
                colorScheme.labelsStylePoiShopsTextColorMassage,
                colorScheme.labelsStylePoiShopsTextColor,
            ],
            'icon-color': [
                'case',
                [
                    'in',
                    ['get', 'shop'],
                    [
                        'literal',
                        [
                            'alcohol',
                            'bakery',
                            'beverages',
                            'butcher',
                            'coffee',
                            'confectionery',
                            'convenience',
                            'deli',
                            'dairy',
                            'greengrocer',
                            'tea',
                            'department_store',
                            'supermarket',
                            'bag',
                            'clothes',
                            'fabric',
                            'jewelry',
                            'shoes',
                            'charity',
                            'second_hand',
                            'variety_store',
                            'beauty',
                            'chemist',
                            'hairdresser',
                            'medical_supply',
                            'optician',
                            'perfumery',
                            'florist',
                            'garden_centre',
                            'houseware',
                            'paint',
                            'trade',
                            'bed',
                            'carpet',
                            'furniture',
                            'interior_decoration',
                            'computer',
                            'electronics',
                            'hifi',
                            'mobile_phone',
                            'bicycle',
                            'boat',
                            'car',
                            'car_repair',
                            'motorcycle',
                            'outdoor',
                            'sports',
                            'tyres',
                            'art',
                            'music',
                            'musical_instrument',
                            'photo',
                            'video',
                            'video_games',
                            'gift',
                            'newsagent',
                            'stationery',
                            'ticket',
                            'bookmaker',
                            'copyshop',
                            'laundry',
                            'pet',
                            'tobacco',
                            'toys',
                            'travel_agency',
                        ],
                    ],
                ],
                colorScheme.labelsStylePoiShopsIconColorLiteral,
                ['==', ['get', 'shop'], 'massage'],
                colorScheme.labelsStylePoiShopsIconColorMassage,
                colorScheme.labelsStylePoiShopsIconColor,
            ],
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiShopsIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiShopsTextHaloColor,
        },
    },
    {
        id: 'poi_restaurants',
        type: 'symbol',
        filter: [
            'all',
            ['in', ['get', 'amenity'], ['literal', ['restaurant', 'food_court']]],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'restaurant',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiRestaurantsTextColor,
            'icon-color': colorScheme.labelsStylePoiRestaurantsIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiReaturantsIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiRestaurantsTextHaloColor,
        },
    },
    {
        id: 'poi_fast-food',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'fast_food'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'fast_food',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiFastFoodTextColor,
            'icon-color': colorScheme.labelsStylePoiFastFoodIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiFastFoodIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiFastFoodTextHaloColor,
        },
    },
    {
        id: 'poi_bars/pubs',
        type: 'symbol',
        filter: [
            'all',
            ['in', ['get', 'amenity'], ['literal', ['bar', 'biergarten', 'pub']]],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiBarPubTextColor,
            'icon-color': colorScheme.labelsStylePoiBarPubIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiBarPubIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiBarPubTextHaloColor,
        },
    },
    {
        id: 'poi_pharmacies',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'pharmacy'],
            ['>=', ['zoom'], 16],
        ],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            'icon-image': 'pharmacy',
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-size': 11,
            'text-field': ['get', 'name'],
            'text-anchor': 'top',
            visibility: 'visible',
            'text-optional': true,
            'text-max-width': 5,
        },
        paint: {
            'text-color': colorScheme.labelsStylePoiPharmacieTextColor,
            'icon-color': colorScheme.labelsStylePoiPharmacieIconColor,
            'icon-opacity': 1,
            'icon-translate-anchor': 'map',
            'icon-halo-color': colorScheme.labelsStylePoiPharmacieIconHaloColor,
            'icon-halo-width': 1,
            'text-halo-width': 1,
            'text-halo-color': colorScheme.labelsStylePoiPharmacieTextHaloColor,
        },
    },
    {
        id: 'zoo_labels',
        type: 'symbol',
        filter: ['all', ['==', 'tourism', 'zoo']],
        source: 'baremaps',
        'source-layer': 'tourism',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Bold'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                13,
                12,
                16,
                16,
                18,
                20,
            ],
        },
        paint: {
            'text-color': colorScheme.labelsStyleZooLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleZooLabelsTextHaloColor,
            'text-halo-width': 1,
        },
    },
    {
        id: 'monument_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'historic'], 'monument'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'building',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'historic'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'icon-allow-overlap': true,
            'text-font': ['Noto Sans Regular'],
            'text-field': ['get', 'name'],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': colorScheme.labelsStyleMonumentLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleMonumentLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleMonumentLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleMonumentLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'cemetery_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'landuse'], 'cemetery'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                10,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleCemeteryLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleCemeteryLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'forest_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'landuse'], 'forest'], ['>=', ['zoom'], 15]],
        source: 'baremaps',
        'source-layer': 'landuse',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                12,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleForestLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleForestLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'stadium_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'leisure'], 'stadium'],
            ['>=', ['zoom'], 15],
        ],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                15,
                9,
                17,
                16,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleStadiumLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleStadiumLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'park_labels',
        type: 'symbol',
        filter: ['all', ['==', ['get', 'leisure'], 'park'], ['>=', ['zoom'], 14]],
        source: 'baremaps',
        'source-layer': 'leisure',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'name'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                14,
                10,
                17,
                18,
            ],
            'text-max-width': 4,
        },
        paint: {
            'text-color': colorScheme.labelsStyleParkLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleParkLabelsTextHaloColor,
            'text-halo-width': 0.8,
        },
    },
    {
        id: 'hospital_labels',
        type: 'symbol',
        filter: [
            'all',
            ['==', ['get', 'amenity'], 'hospital'],
            ['>=', ['zoom'], 14],
        ],
        source: 'baremaps',
        'source-layer': 'amenity',
        layout: {
            visibility: 'visible',
            'icon-image': ['get', 'amenity'],
            'icon-size': 1,
            'icon-anchor': 'bottom',
            'text-font': ['Noto Sans Regular'],
            'text-field': ['step', ['zoom'], '', 14, '', 15, ['get', 'name']],
            'text-size': 11,
            'text-max-width': 4,
            'text-anchor': 'top',
            'text-optional': true,
        },
        paint: {
            'text-color': colorScheme.labelsStyleHopitalLabelsTextColor,
            'text-halo-color': colorScheme.labelsStyleHopitalLabelsTextHaloColor,
            'text-halo-width': 0.8,
            'icon-color': colorScheme.labelsStyleHopitalLabelsIconColor,
            'icon-halo-color': colorScheme.labelsStyleHopitalLabelsIconHaloColor,
            'icon-halo-width': 1,
        },
    },
    {
        id: 'motorway_junction_ref',
        type: 'symbol',
        filter: ['all', ['==', 'highway', 'motorway_junction']],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['get', 'ref'],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                10,
                9,
                11,
                9.5,
                12,
                10,
            ],
        },
        maxzoom: 12,
        paint: {
            'text-color': colorScheme.labelsStyleMotorwayJunctionRefTextColor,
            'text-halo-color': colorScheme.labelsStyleMotorwayJunctionRefTextHaloColor,
            'text-halo-width': 1.2,
        },
    },
    {
        id: 'motorway_junction_name',
        type: 'symbol',
        filter: ['all', ['==', 'highway', 'motorway_junction']],
        source: 'baremaps',
        'source-layer': 'points',
        layout: {
            visibility: 'visible',
            'text-font': ['Noto Sans Italic'],
            'text-field': ['format', ['get', 'name'], '\n', ['get', 'ref']],
            'text-size': [
                'interpolate',
                ['exponential', 1.2],
                ['zoom'],
                12,
                9,
                15,
                10,
                18,
                11,
            ],
        },
        minzoom: 12,
        paint: {
            'text-color': colorScheme.labelsStyleMotorwayJunctionNameTextColor,
            'text-halo-color': colorScheme.labelsStyleMotorwayJunctionNameTextHaloColor,
            'text-halo-width': 1.2,
        },
    },
]
