DROP INDEX IF EXISTS osm_relations_tags_index;
DROP INDEX IF EXISTS osm_relations_geom_index;

DROP VIEW IF EXISTS osm_relations_z20 CASCADE;
DROP VIEW IF EXISTS osm_relations_z19 CASCADE;
DROP VIEW IF EXISTS osm_relations_z18 CASCADE;
DROP VIEW IF EXISTS osm_relations_z17 CASCADE;
DROP VIEW IF EXISTS osm_relations_z16 CASCADE;
DROP VIEW IF EXISTS osm_relations_z15 CASCADE;
DROP VIEW IF EXISTS osm_relations_z14 CASCADE;
DROP VIEW IF EXISTS osm_relations_z13 CASCADE;

DROP MATERIALIZED VIEW IF EXISTS osm_relations_z12 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z11 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z10 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z9 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z8 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z7 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z6 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z5 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z4 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z3 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z2 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_relations_z1 CASCADE;
