DROP INDEX IF EXISTS osm_nodes_tags_index;
DROP INDEX IF EXISTS osm_nodes_geom_index;

DROP VIEW IF EXISTS osm_nodes_z20 CASCADE;
DROP VIEW IF EXISTS osm_nodes_z19 CASCADE;
DROP VIEW IF EXISTS osm_nodes_z18 CASCADE;
DROP VIEW IF EXISTS osm_nodes_z17 CASCADE;
DROP VIEW IF EXISTS osm_nodes_z16 CASCADE;
DROP VIEW IF EXISTS osm_nodes_z15 CASCADE;
DROP VIEW IF EXISTS osm_nodes_z14 CASCADE;

DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z13 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z12 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z11 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z10 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z9 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z8 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z7 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z6 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z5 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z4 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z3 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z2 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS osm_nodes_z1 CASCADE;
