title: Baremaps
repository: baremaps/baremaps
exclude:
  - examples/target
  - examples/test
  - examples/examples.iml
  - examples/pom.xml
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter