DROP VIEW IF EXISTS globaladm0_z20 CASCADE;
DROP VIEW IF EXISTS globaladm0_z19 CASCADE;
DROP VIEW IF EXISTS globaladm0_z18 CASCADE;
DROP VIEW IF EXISTS globaladm0_z17 CASCADE;
DROP VIEW IF EXISTS globaladm0_z16 CASCADE;
DROP VIEW IF EXISTS globaladm0_z15 CASCADE;
DROP VIEW IF EXISTS globaladm0_z14 CASCADE;

DROP MATERIALIZED VIEW IF EXISTS globaladm0_z13 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z12 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z11 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z10 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z9 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z8 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z7 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z6 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z5 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z4 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z3 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z2 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm0_z1 CASCADE;

