DROP VIEW IF EXISTS globaladm1_z20 CASCADE;
DROP VIEW IF EXISTS globaladm1_z19 CASCADE;
DROP VIEW IF EXISTS globaladm1_z18 CASCADE;
DROP VIEW IF EXISTS globaladm1_z17 CASCADE;
DROP VIEW IF EXISTS globaladm1_z16 CASCADE;
DROP VIEW IF EXISTS globaladm1_z15 CASCADE;
DROP VIEW IF EXISTS globaladm1_z14 CASCADE;

DROP MATERIALIZED VIEW IF EXISTS globaladm1_z13 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z12 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z11 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z10 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z9 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z8 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z7 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z6 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z5 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z4 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z3 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z2 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm1_z1 CASCADE;

