DROP VIEW IF EXISTS globaladm2_z20 CASCADE;
DROP VIEW IF EXISTS globaladm2_z19 CASCADE;
DROP VIEW IF EXISTS globaladm2_z18 CASCADE;
DROP VIEW IF EXISTS globaladm2_z17 CASCADE;
DROP VIEW IF EXISTS globaladm2_z16 CASCADE;
DROP VIEW IF EXISTS globaladm2_z15 CASCADE;
DROP VIEW IF EXISTS globaladm2_z14 CASCADE;

DROP MATERIALIZED VIEW IF EXISTS globaladm2_z13 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z12 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z11 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z10 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z9 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z8 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z7 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z6 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z5 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z4 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z3 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z2 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS globaladm2_z1 CASCADE;

