name: Publish snapshot artifacts

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish snapshot artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          server-id: apache
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Deploy snapshots
        env:
          SERVER_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn deploy
