name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-github:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:

      # Checkout code, set up Java 17, build project, and extract version
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Extract version
        run: echo ::set-output name=value::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: version
      - name: Build project
        run: mvn install -B

      # Create a GitHub release draft
      - name: Setup GitHub CLI
        uses: actions/setup-cli@v1
        with:
          version: latest
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Create GitHub Release
        id: create_release
        run: |
          gh release create "${{ github.ref }}" \
            --draft \
            --prerelease \
            --title "Apache Baremaps ${{ steps.version.outputs.value }} (incubating)" \
            --repo ${{ github.repository }} \
            --generate-notes

      # Sign, hash, and upload source release to GitHub
      - name: Sign and hash source release
        shell: bash
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch
          shasum -a 512 "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz" > "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz.sha512"
          gpg --no-tty --quiet --pinentry-mode loopback --default-key "${{ secrets.GPG_KEY_ID }}" --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz.asc" --detach-sign --armor "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz"
      - name: Upload source release
        id: upload-source-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz
          asset_name: apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload source release sha512
        id: upload-source-release-sha512
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz.sha512
          asset_name: apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz.sha512
          asset_content_type: text/plain
      - name: Upload source release asc
        id: upload-source-release-asc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz.asc
          asset_name: apache-baremaps-${{ steps.version.outputs.value }}-incubating-src.tar.gz.asc
          asset_content_type: text/plain

      # Sign, hash, and upload binary release to GitHub
      - name: Sign and hash source release
        shell: bash
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch
          shasum -a 512 "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz" > "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz.sha512"
          gpg --no-tty --quiet --pinentry-mode loopback --default-key "${{ secrets.GPG_KEY_ID }}" --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz.asc" --detach-sign --armor "./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz"
      - name: Upload binary release
        id: upload-binary-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz
          asset_name: apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload binary release sha512
        id: upload-binary-release-sha512
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz.sha512
          asset_name: apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz.sha512
          asset_content_type: text/plain
      - name: Upload binary release asc
        id: upload-binary-release-asc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./baremaps-cli/target/apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz.asc
          asset_name: apache-baremaps-${{ steps.version.outputs.value }}-incubating-bin.tar.gz.asc
          asset_content_type: text/plain
